### ISSUE TITLE
Jobs are not disappearing and are listed until started new.

### ISSUE THREAD

**Issue by cswh** [energiekollektiv/openmod.sh#38] opened 2017-03-17 10:08 UTC

**Comment by gnn** [comment] 2017-03-17 17:42
That is correct. How should I change this behavior? The easiest thing would be to add a `Cleanup` button at the bottom of the list that removes jobs which are no longer running. Would that be OK?

**Comment by cswh** [comment] 2017-03-21 18:08
the cleanup button should remove the jobs which are not running anymore and additional the jobs which are already cancelled and shall not run at all.
additinoally it would be easier for the user, if a job which was already cancelled is not listed as queued but as "cancelled".
is that possible?

**Comment by gnn** [comment] 2017-03-21 18:20
> the cleanup button should remove the jobs which are not running anymore and additional the jobs which are already cancelled and shall not run at all.

OK, that's how I envisioned it anyway. Have been working on that till now, but for some reason, job status updates are not working as they did before. Have to figure out why. Gonna finish that tomorrow.

> additinoally it would be easier for the user, if a job which was already cancelled is not listed as queued but as "cancelled".
> is that possible?

Yeah, most definitely. I already implemented that and had it working, but it seems the changes are gone. Going to check why. Maybe I forgot to push. Will post an update later, when I'm able to check.

**Comment by gnn** [comment] 2017-03-22 19:20
I implemented the cleanup button. You can just merge it into `dev` via PR #43.
But please test it out beforehand because I checked that any job which gets cancelled is immediately marked `Cancelled.` and no longer `Queued.`. The problem is, that this should've been in there last day already and only didn't work for me because I had local changes which messed things up. If it didn't work yesterday for you, there must be something deeper which didn't get fixed in my branch, so I'm a little bit cautious.

**Closed** 2017-03-23 05:13 UTC
Labels: bug, urgent
